import = [
  "~/atlas/repos/dotfiles/alacritty/catppuccin-frappe.toml"
]

[window]
option_as_alt = "OnlyLeft"
opacity = 0.999
# decorations = "Buttonless"  # remove title bar

[keyboard]
bindings = [
  { key = "Left",  mods = "Command", chars = "\u001bOH" },
  { key = "Right", mods = "Command", chars = "\u001bOF" },
]
