[user]
email = "ben@benburk.me"
username = "benburk"
name = "Ben Burk"

[init]
defaultBranch = "main"

[delta]
side-by-side = true

[core]
editor = "hx"
pager = "delta"
excludesfile = "~/.gitignore_global"
