# theme = "catppuccin_frappe"
theme = "catppuccin_frappe_no_bg"

[editor]
line-number = "relative"
true-color = true
auto-save = true
# shell = ["fish", "-c"]

# soft-wrapping
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
text-width = 80
rulers = [80]
smart-tab.enable = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal.space]
z = ":toggle soft-wrap.enable"
'=' = ":format"
